### ISSUE TITLE
Don't store credentials in NSUserDefaults

### ISSUE THREAD

**Issue by iMinichrispy** [calda/T-Squared#3]
Storing usernames and passwords in NSUserDefaults is a really, really bad idea, even if you're encrypting them: https://www.andyibanez.com/nsuserdefaults-not-for-sensitive-data/. You should always store credentials in the iOS keychain instead.

All data stored in NSUserDefaults is saved in plain text, which makes it really easy for an attacker to retrieve the info they need to get a user's credentials. And while encrypting the passwords yourself might seem like a good idea, it gets bad quickly when the inputs used to encrypt and decrypt this data are readily accessible:
Key: Cal<3sEncryption
IV: TrustMePlsssssss

This is why letting iOS handle these things is a good idea.

**Comment by calda** [comment]
Well shit (this is kinda embarrassing). I didn't realize it was so easy to get access to files in an app bundle. Thanks for calling me out, though. A new version with proper security will be up soon.

**Comment by iMinichrispy** [comment]
No worries, thanks for being so quick to come up with a fix. cbabe9d looks good to me.
