### ISSUE TITLE
no license? oh no

### ISSUE THREAD

**Issue by hugabor** [calda/T-Squared#6]
don't let me steal it

**Comment by calda** [comment]
There used to be a license but it was too permissible so i just got rid of it

**Comment by marcospolanco** [comment]
I'm a student also working on an app that could use some of the underlying code for pulling assignments for given classes. Would it be possible to retrieve the code under the MIT License for this case? We can connect directly if you like.

**Comment by calda** [comment]
@marcospolanco This codebase is a bit old and definitely not up to par anymore. I think it'd be in your best interested to rewrite the bits you're interested in -- but you're welcome to use the code as a reference.

**Comment by calda** [comment]
Fixed in a2f82f6 -- added GNU v3.0

**Comment by calda** [comment]
cc: @LumingYin

**Comment by LumingYin** [comment]
Thanks, Cal!
